## Installing Packages

In [1]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import requests

## Web Scrapping

In [2]:
r = requests.get("https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M")
soup = BeautifulSoup(r.content, 'xml')
table = soup.find("table")
header = [head.findAll(text=True)[0].strip() for head in table.find_all("th")]
data   = [[td.findAll(text=True)[0].strip() for td in tr.find_all("td")]for tr in table.find_all("tr")]
data    = [row for row in data if len(row) == 3]
postal_df = pd.DataFrame(data,columns=header)
postal_df

,Postal Code,Borough,Neighborhood
0,M1A,Not assigned,Not assigned
1,M2A,Not assigned,Not assigned
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
...,...,...,...
175,M5Z,Not assigned,Not assigned
176,M6Z,Not assigned,Not assigned
177,M7Z,Not assigned,Not assigned
178,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."
179,M9Z,Not assigned,Not assigned

## DataFrame cleaning

In [3]:
#drop rows where 'Borough is Not Assigned'
for index, value in enumerate(postal_df['Borough']=='Not assigned'):
    if value:
        postal_df.drop([index], axis=0, inplace=True)
#If a cell has a borough but a Not assigned neighborhood, then the neighborhood will be the same as the borough
postal_df.loc[postal_df['Neighborhood'] == 'Not assigned', ['Neighborhood']] = postal_df['Borough']

In [4]:
#More than one neighborhood can exist in one postal code area
postal_df.groupby(['Postal Code','Borough'])['Neighborhood'].apply(', '.join).reset_index()

,Postal Code,Borough,Neighborhood
0,M1B,Scarborough,"Malvern, Rouge"
1,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek"
2,M1E,Scarborough,"Guildwood, Morningside, West Hill"
3,M1G,Scarborough,Woburn
4,M1H,Scarborough,Cedarbrae
...,...,...,...
98,M9N,York,Weston
99,M9P,Etobicoke,Westmount
100,M9R,Etobicoke,"Kingsview Village, St. Phillips, Martin Grove ..."
101,M9V,Etobicoke,"South Steeles, Silverstone, Humbergate, Jamest..."
102,M9W,Etobicoke,"Northwest, West Humber - Clairville"

In [5]:
postal_df.shape

(103, 3)